version: '3'
services:
  webserver:
    build: .
    command: "npm run start:webserver"
    ports:
      - "3000:80"
    depends_on:
      - db
    environment:
      - PROC_TITLE=webserver
      - SEED_COUNT=100
      - DB_CONNECTION_STRING=postgres://db_user:db_password@db:5432/webserver_database

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=webserver_database
